### ISSUE TITLE
Git release tag: bigloo-4.5b

### ISSUE THREAD

**Issue by kpcyrd** [manuel-serrano/bigloo#116]
hello, I'm currently looking for an alternative download location of the `bigloo-4.5b` soure code as part of an effort in Arch Linux to [retire downloading source code from `ftp://`](https://archlinux.org/todo/find-alternative-origin-for-ftp-resources/), with bigloo being the last remaining package.

I'm looking for an alternative location for this file, preferably over https:

```
ftp://ftp-sop.inria.fr/indes/fp/Bigloo/bigloo-4.5b.tar.gz
```

Pushing a git tag for this version would also work, the Arch Linux build system can fetch source code from git.

Thanks!

**Comment by kpcyrd** [comment]
Any updates here? Bigloo is still the last package left on this todo list and I couldn't manage to locate the source code on `https://www-sop.inria.fr`.

**Comment by Strit** [comment]
I noticed that this github repo has a branch for each release. Maybe the zip of the branches can be of use here?

https://github.com/manuel-serrano/bigloo/archive/refs/heads/4.5b.zip

**Comment by manuel-serrano** [comment]
If you are simply looking for an ftp alternative, you can download the tarball here:

   http://www-sop.inria.fr/indes/fp/Bigloo/download/bigloo-latest.tar.gz

This is the "official" URL for the Bigloo tarballs.
Please let me know if this is what you are looking for.

Best,

**Comment by kpcyrd** [comment]
`bigloo-latest.tar.gz` isn't what I'm looking for unfortunately because it sounds like it may change to a version other than 4.5b at some point in the future.

**Comment by manuel-serrano** [comment]
I see. You can now use http://www-sop.inria.fr/indes/fp/Bigloo/download/bigloo-4.5b.tar.gz

**Comment by kpcyrd** [comment]
Thanks, I've rebuilt the package and ftp:// has been retired from Arch Linux. :)
