### ISSUE TITLE
certificate? and private-key? undefined

### ISSUE THREAD

**Issue by svenha** [manuel-serrano/bigloo#13]
The functions `certificate?` and `private-key?`, which are documented in section 5.7.5, are not available from (library ssl).

**Comment by manuel-serrano** [comment]
Hi Sven,

You are right. The documentation needs an update. Certificate and private-key are classes and the documentation has been written at a time where predicates where automatically generated for classes.
They no longer are a (certificate? expr) should now be written (isa? expr certificate). I will fixe the
documentation accordingly.
