### ISSUE TITLE
bglstone: qsort benchmark is not informative due to a bug

### ISSUE THREAD

**Issue by svenha** [manuel-serrano/bigloo#14]
bigloo/qsort.scm in bglstone confuses the number of runs with the size of the vector to be sorted. Hence, runtimes are tiny and not informative. I attach a fixed file that also tries to increase the task difficulty and to avoid too aggressive optimizations (it uses the result of calls). The necessary fix affects only the function doit.
[qsort.scm.txt](https://github.com/manuel-serrano/bigloo/files/2612241/qsort.scm.txt)

**Comment by manuel-serrano** [comment]
Thanks I have applied the modifications to the Bigloo, Gambit, and Kawa sort. It will make the comparison with older systems impossible but the benefit of having significant numbers justifies the
modifications.
