### ISSUE TITLE
Installing bigloo on Ubuntu 18.10

### ISSUE THREAD

**Issue by ak-1** [manuel-serrano/bigloo#22]
I tried to use the Ubuntu package on Ubuntu 18.10, but got this:

    E: The repository 'ftp://ftp-sop.inria.fr/indes/fp/Hop/ubuntu precise Release' does not have a Release file.
    N: Updating from such a repository can't be done securely, and is therefore disabled by default.

Not sure if this would work anyway since it's for another Ubuntu release.

**Comment by svenha** [comment]
As you said, the files are for quite old Ubuntu versions and are from 2012. You must install bigloo from a source tar file (as you try in issue #23).

**Comment by ak-1** [comment]
All right, thank you for the clarification.
