### ISSUE TITLE
Does the autoconf test openssl-tls1.3 use the specified C compiler?

### ISSUE THREAD

**Issue by svenha** [manuel-serrano/bigloo#34]
Some autoconf tests respect the C compiler passed in by CC=..... But some do not, e.g. openssl-tls1.3 (which makes TLS 1.3 unavailable for me). For example if using CC=gccx32, `cctest` is called correctly as:

    ./autoconf/runtest -v1 -- cctest "--cc=gccx32"

**Comment by manuel-serrano** [comment]
I'm not able to reproduce the problem. The tests are executed via autoconf/runtest that defines CC.
I cannot reproduce the problem where tests, for instance openssl that you mentioned are using a wrong CC version. Could you elaborate? Thanks.

**Comment by svenha** [comment]
OK, I have investigated the issue a little more. The problem for openssl-tls1.3 is that TLSv1_3_client_method is no defined in my openssl installation. What version of openssl should work and which header file defines this function?

**Comment by manuel-serrano** [comment]
I don't think it is available yet but it has been reported here that it will soon be. The Bigloo configuration is just one step ahead :-)

**Comment by svenha** [comment]
OK, let's see again when a matching openssl version is released.
