### ISSUE TITLE
Test failure on Raspberry Pi 4 running Gentoo

### ISSUE THREAD

**Issue by martin-ward** [manuel-serrano/bigloo#55]
I just ran "make" and "make test" on my Raspberry Pi 4 running Gentoo
and got one test failure: 

```
*** WARNING:bigloo:link
No Bigloo module found for -- objs_c/c-file.o
Static Recette Done...
-------------------------------
make[2]: Leaving directory '/home/martin/src/bigloo-unstable/recette'
vital.scm:
bps.scm:
cell.scm:
module.scm:
hash.scm:
bool.scm:
number.scm:
flonum.scm:
bignum.scm:
list.scm:
vector.scm:
srfi4.scm:
struct.scm:
print.scm:
char.scm:
string.scm:
kwote.scm:
case.scm:
bind-exit.scm:
vararity.scm:
apply.scm:
globalisation.scm:
kapture.scm:
filtre.scm:
match.scm:
rgc.scm:
rgc_trap.scm:
rgc-jm.scm:
rgc-eval.scm:
rgc-insert.scm:
lalr.scm:
port.scm:
mmap.scm:
read.scm:
callcc.scm:
fringe.scm:
wind.scm:
dsssl.scm:
tail.scm:
external-c.scm:
sqic.scm:
eval.scm:
inline.scm:
letrec.scm:
macro.scm:
define.scm:
cse.scm:
error.scm:
33.error(with-handler.11) fail: provided [(+inf.0 . +inf.0)], wanted [(a . b)]
include.scm:
0cfa.scm:
sua.scm:
alias.scm:
object.scm:
object-sans.scm:
object5.scm:
object5-sans.scm:
hygiene.scm:
peek.scm:
unicode.scm:
optim.scm:
pregexp.scm:
system.scm:
date.scm:
weakptr.scm:
crc.scm:
process.scm:
wind.scm:

------------------------------
recette failed: 1 error(s) occurred.
make[1]: *** [Makefile:639: c-test] Error 255
make[1]: Leaving directory '/home/martin/src/bigloo-unstable'
make: *** [Makefile:623: test] Error 2 
```

**Comment by svenha** [comment]
Same test result under Ubuntu 20.10 for Raspberry. The culprit seems to be a gmp bug that is already fixed upstream. I installed gmp-6.2.1 locally (packaged version is 6.2.0) and the error went away.

**Comment by manuel-serrano** [comment]
Hi Martin. 

I have updated gmp version to 6.2.1 and I have tested on a Raspberry Pi 3.
The problem you have reported does not show up. I don't know if this is
because the new gmp version solved it or because there is a difference
between the Pi 3 and Pi 4 that makes it work on one machine but not
the other. Do you think you could try the version I have just uploaded
on the web site and let us know if the problem is gone for you too?
Thanks in advance.

**Comment by svenha** [comment]
Hi Manuel.

I tried the new bigloo version 4.4a-2 today on a Raspberry Pi 4 B. The problem remains. (BTW: Ubuntu 20.10 comes with gcc 10.2.)

What is your OS and gcc? But your hypothesis about Pi 3 vs Pi 4 might be true.

**Comment by martin-ward** [comment]
My pi 4 is running a version of Gentoo which is no longer being updated:

[https://forums.gentoo.org/viewtopic-p-8522963.html#8522963](url)
[https://forums.gentoo.org/viewtopic-p-8521703.html#8521703](url)

My colleague is running Raspberry Pi OS and has version 6.1.2+dfsg-4
of libgmp and all tests succeeded for him.

**Comment by manuel-serrano** [comment]
For developping I'm using two configurations:
  Linux x86_64/Debian-10, gcc 8.3.0
  Linux x86_64/Debian-bullseye, gcc 10.2.0
The raspberry is:
  Linux ARMv7/Debian-10 (Buster), gcc 8.3.0

**Comment by martin-ward** [comment]
I am still getting the error with the latest unstable (Sat, 14 Nov 2020 08:48:13)

**Comment by manuel-serrano** [comment]
Hum. Too bad I don't have my Pi4 with me. Unfornately, in France, the lockdown is likely to last until December so I'm unlikely
to be able to solve that problem until then.

**Comment by manuel-serrano** [comment]
I have forgotten to close that one. It has been fixed (the test was wrong) and everything should be now fine on Pi4 platforms.
