### ISSUE TITLE
fprintf do not work like describe in the documentation

### ISSUE THREAD

**Issue by PFOllagnon** [manuel-serrano/bigloo#57]
Description:

_fprint output-port obj ...
This function is the same as print except that a port is provided._ 

1) we can only put one obj (other ones are omitted)
2) it doesn't add a new-line

So it is currently the same as write (arguments are just swapped)

**Comment by svenha** [comment]
Can you please check your post: `fprint` or `fprintf`?
I see no problems with `fprint`:

     (fprint (current-output-port) "abc" "def")

Prints:

     abcdef

**Comment by PFOllagnon** [comment]
OOOPS !
You are right. I mixed up both functions. :-/
