### ISSUE TITLE
Parallel test issue (unverified)

### ISSUE THREAD

**Issue by xgqt** [manuel-serrano/bigloo#75]
Hello!
We hit a weird bug on the Gentoo test CI, we assume this is a issue of running more then one job for tests.
What do you think of this issue @manuel-serrano?

Bug: https://bugs.gentoo.org/836286

**Comment by manuel-serrano** [comment]
I have no idea. Checking the Makefile or the recette directory, the dependencies seem correct. I have no idea where the problem could come from. I would need a confirmation that the problem remains. In the meantime, I will close this issue.
