### ISSUE TITLE
https://www-sop.inria.fr returns 403 Error: Forbidden 

### ISSUE THREAD

**Issue by dlahman** [manuel-serrano/bigloo#78]
Just noticed that the main site that's referenced (inria) returns 403 errors when visited. I'm not sure when this changed (couldn't have been that long ago) but I can't access anything related to bigloo on the site - including the pre-compiled versions and documentation.

Example: https://www-sop.inria.fr/indes/fp/Bigloo/doc/bigloo.html
Returns 403 Forbidden

**Comment by svenha** [comment]
At the moment, this URL will show the bigloo documentation for version 4.3g. Better, but not perfect :-)

**Comment by manuel-serrano** [comment]
The URL you mentioned has been replaced with:
  http://www-sop.inria.fr/indes/fp/Bigloo/manual.html

**Comment by lassik** [comment]
https://www-sop.inria.fr/indes/fp/Bigloo/ is up. https://hop.inria.fr/ is down.

**Comment by manuel-serrano** [comment]
Try http://hop.inria.fr
That is http not https.
